token = '' #сюда вставляете токен своей группы

help_message = 'памагите вопросами убивают'

random_message = ['рандомные фразочки', 'на рандомные сообщения']

heads_and_tails = ['орешка вин','орел вин']