token = '' #сюда вставляете токен своей группы
group_id = '' #сюда вставляете id вашей группы

help_message = 'могу тебе рандомные фразочки кинуть и кинуть монетку по команде "орел или решка"'

random_message = ['рандомные фразочки', 'на рандомные сообщения']

heads_and_tails = ['орешка вин','орел вин']
