token = '' #сюда вставляете токен своей группы
group_id = '' #сюда вставляете id вашей группы

help_message = 'я могу тебе мем сделать из команды "мем", еще могу тебе рандомные фразочки кинуть и кинуть монетку по команде "орел или решка"'

random_message = ['что ты только что высрал', 'зачем мне эта информация', 'я бот, а не человек, я тебя не понимаю', 'капец ты дурачок', 'ясно все с тобой', 'да', 'пизда' ,'нет', 'киркорова ответ']

heads_and_tails = ['орешка вин','орел вин']