
token = '' #Here Token
group_id = '' #Here Group ID

help_message = 'могу тебе рандомные фразочки кинуть и кинуть монетку по команде "орел или решка"'

random_message = ['рандомные фразочки', 'на рандомные сообщения']

heads_and_tails = ['орешка вин','орел вин']
